server {
    listen 80;
    server_name waves.cam;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name waves.cam;

    ssl_certificate /etc/letsencrypt/live/waves.cam/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/waves.cam/privkey.pem;

    root /home/ec2-user/waves/public;
    index index.html;

    location / {
        proxy_pass http://localhost:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
